steps:
- name: 'gcr.io/cloud-builders/gcloud'
-args: [— functions — deploy — — runtime=nodejs8 — — trigger-http — — source=./ — — entry-point=helloCiCd  — helloCiCd]
-id: 'deploying-a-serverless-function'

